apiVersion: v1
kind: Namespace
metadata:
  name: b-team
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: b-team
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
    - containerPort: 80